In [3]:
from datetime import datetime
import pandas as pd
d_parser = lambda x : datetime.strptime(x,"%d.%m.%Y %H:%M:%S.%f")
# Read your data into a DataFrame (replace this with your actual data loading logic)
df = pd.read_csv('./00.24.56_01.24.56.txt', sep='\t', parse_dates=['Time'], date_parser=d_parser)
df.set_index('Time', inplace=True)
df.head()

,[1:0],[1:1],[1:2],[1:3],[1:4],[1:5],[1:6],[1:7],[1:8],[1:9],...,[26.114],[26.115],[26.116],[26.117],[26.118],[26.119],[26.120],[26.121],[26.122],[26.123]
Time,,,,,,,,,,,,,,,,,,,,,
2024-02-01 00:24:56.530,-28033,1481,-6423,-302,0.0,0.0,0,496,496,496,...,0,0,0,0,1,1,1,0,0,0
2024-02-01 00:24:56.540,-28033,1481,-6423,-302,0.0,0.0,0,496,496,496,...,0,0,0,0,1,1,1,0,0,0
2024-02-01 00:24:56.550,-28033,1481,-6423,-302,0.0,0.0,0,496,496,496,...,0,0,0,0,1,1,1,0,0,0
2024-02-01 00:24:56.560,-28033,1481,-6423,-302,0.0,0.0,0,496,496,496,...,0,0,0,0,1,1,1,0,0,0
2024-02-01 00:24:56.570,-28033,1481,-6423,-302,0.0,0.0,0,496,496,496,...,0,0,0,0,1,1,1,0,0,0